{% set name = "click" %}
{% set version = "8.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/click-{{ version }}.tar.gz
  sha256: 7682dc8afb30297001674575ea00d1814d808d6a36af415a82bd481d37ba7b8e

build:
  number: 0
  # trigger 2
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - colorama  # [win]
    - importlib-metadata  # [py<38]

test:
  imports:
    - click
  requires:
    - pip
  commands:
    # temporarily skipping pip check on win and pypy build because of bizarre tqdm issue
    - pip check  # [not (win and python_impl == 'pypy')]

about:
  home: https://palletsprojects.com/p/click
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Python composable command line interface toolkit
  dev_url: https://github.com/pallets/click
  doc_url: https://click.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - xylar
