{% set version = "8.0.2" %}

package:
  name: click
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/click/click-{{ version }}.tar.gz
  sha256: 7027bc7bbafaab8b2c2816861d8eb372429ee3c02e193fc2f93d6c4ab9de49c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - colorama  # [win]
    - importlib-metadata  #[py<38]

test:
  imports:
    - click

about:
  home: https://palletsprojects.com/p/click
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Python composable command line interface toolkit
  dev_url: https://github.com/pallets/click
  doc_url: https://click.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - xylar
