{% set version = "8.0.3" %}

package:
  name: click
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/click/click-{{ version }}.tar.gz
  sha256: 410e932b050f5eed773c4cda94de75971c89cdb3155a72a0831139a79e5ecb5b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - colorama  # [win]
    - importlib-metadata  #[py<38]

test:
  imports:
    - click
  requires:
    - pip
    - python <3.10
    - colorama  # [win]
  commands:
    # temporarily skipping pip check on win and pypy build because of bizarre tqdm issue
    - pip check  # [not (win and python_impl == 'pypy')]

about:
  home: https://palletsprojects.com/p/click
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Python composable command line interface toolkit
  dev_url: https://github.com/pallets/click
  doc_url: https://click.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - xylar
