travis:
  secure:
    BINSTAR_TOKEN: mU9LaODfctcm0U8knlOpW/JOiz2W1DGoFsxHzgOLq6Irhplct43IOLUWuAdkNtBKtvzWSr9hF3jqLVS0QYxZo0Rkodrt/k/aYTQn6nP/ETW3Z24HwVAmTal+73tHXIXKISUDCPmlPYN12MXdJxbdXHbIIoBBPOlvS69+VA1+3IxA0qbaEXZNKMLMo4rU/jyUYXgAuHFkc5kOJvLIpKX3mhvri0YQ08oUHo+6GFZVRYQAGR3aZlIxUHt7aaOCPtrhkzlew8grq/bS3imoGYFzTKYZuLqDXuDXi/6ylo0vimwEIrgRItyY4I3Vy2UhLti1dAbenkItf7AtkMVMtmJ6LXxhXvqZ70lKBoZzTo1Rn8p1AeVB1LxUM38tMozaDtwthn9xEKDAHUwVSpdHeTX6wTHZ2X9uWZ38UrsAvXDbqNPP+Cm8BtUfS3oLL0kzS03NGaxJ9DwaZTxUwU+I3LQJkyN0PAJadP6oFe6+xZnzI/UgVhBBiUCkA4XT1sYKxUG2hf5mt+7Yq+nW6Uub9YWgQQoLgyJHJAlTEmosWNb2djOFA1Zb2L5ZM3+X9j/U3zHd3iyD4eeh3cGiMckHwr9MrBJhAh5EDdVSpj1E4gK8mBVH5+Uk6XETXygRK2981py6mcU1IXO8fc1843f27nQx4EhVeeIf9gqpUEX56gO6oU0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
