travis:
  secure:
    BINSTAR_TOKEN: B8klU92DA188fQPfK/1k+m5W1l7AmCPMRDLm5brwRRVOt6WfwtsKqdSIFaGELittcK1h4kJgfntJ+oAW1J8pHb1EMSbO1kDpGE0RJLggEHpDvLwQRlsRdv8UzA+GAHrC9tjqYca8jDeg/2rmX8dvnRgos/0qfvAh8d7G8pyz6I4DhBHGnctNlrvKNSiJ+NdrRby9Q6Ji4Hi8GF9BN4wPSRjCyJhrcySnaC8Xk2KpVARJGuWKZocUncpAZnviN9Ye28UM9mDYIQ1HhkSIb+WmwqYq5MIAh/iS7UDbpDvH/BnDl/nYYy2+RMxGPnVEcq7KTY+p21HVePfFPC90hMC9h+1+bl2umHKekEsYQ2Yx7y5G/FsPnbbq4Hkq++UNFpZNcfOa0fTOVbt5jp2oEdx3xZZeeYnS4MJ4F3AJ/wW85R1KriQw6eTEmy/k1whJNLNXdEMl8YlbF9nmK1PksMUfdRSF/WeVDciMu9J7lewLX4WKEOJGj3ZeNeMQEX+pcKbyxhhRxT9efRYPEta8URZrcVoAdnalWl42oE6ERITcZGndUyizoHSdy9e4BA/Vn4g8nNWGwkHEUS9+VCnBoIpPTIFiHH3p47dg+pRECToizK9tlxUERVPh1mAe9Xxgr4w9aktYlLJSLauTBIpHg6hwYL0vuQB+Y84Tl1IC/M7tvgY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
